# ===========================================
# Site Settings
# ===========================================
# Header
site_title: Troy's 博客
site_description: 专注于Web开发，现在居住于成都. Happy Coding, Happy Life!
# ---Optional ---
site_avatar: /images/avatar-small.png
artical_license_statement: 本文由http://troyyang.com原创编写，转载请尽量保留版权网址，感谢您的理解与分享!
# ---End Optional ---
menu:
  Home: /
  Archives: /archives
  AboutMe: /about

# display widgets
widgets:
- archives
#- search
#- social_links
- recent_posts
- tagcloud

# widget behavior
archive_type: 'monthly'
show_count: true
# Content
excerpt_link: Read More
# favico 
favicon:

# ===========================================
# Miscellaneous Settings
# ===========================================
# Baidu Analytics
baidu_analytics: 542b4962c3c4035fce9071b7c665f0d2
# Google Analytics
google_analytics: UA-97838175-1
# Disqus
disqus:
  enable: true
  shortname: troyyang-com
  count: true
# changyan
changyan:
  enable: false
  appid:
  appkey:
# duoshuo
duoshuo:
  enable: false
  shortname: troyyang
# Visitors
leancloud_visitors:
  enable: true
  app_id: wzqncxgqp9MCPiPERe3gnX2Q-gzGzoHsz
  app_key: CCtBiqyPtJWupuozt1393AXm

# Search 
# Note: please install hexo-generator-search plugin and config the root _config.yml (not theme's _config.yml) as below value search.json(https://www.npmjs.com/package/hexo-generator-search):
#search:
#  path: search.json
#  field: post
